### ISSUE TITLE
Errors in test file.

### ISSUE THREAD

**Issue by devang-gaur** [fabric8-hdd/supervisor#13]
The test file has a lot of errors.

Just run npm test and see for yourself. I have a PR fix ready for this.

@anmolbabu kindly merge my earlier PRs and then after merging my PR for #12 , I'll raise the PR for this one :)

**Comment by anmolbabu** [comment]
@dev-gaur Have you seen https://github.com/fabric8-hdd/supervisor/issues/3 ?

As suggested in one of my comments on other PRs if you are unsure of what issues are raised, what they relate to and whether or not they are already being worked on by anyone, please do make sure to discuss in one of the sync-up calls...

And by the way except for the issue #3 above, I think there was a missing export from main.js which is also being fixed by @mik-dass in his PR https://github.com/fabric8-hdd/supervisor/pull/9 which he would trim based on inputs from yesterday's Kabal...

Cc: @miteshvp

**Comment by devang-gaur** [comment]
Closed this issue as a duplicate of #3
